add CreateNamedPipe(), ConnectNamedPipe(), DisconnectNamedPipe()
rodrigocfd/windigo pull request #16
Opened 2023-04-03 00:37 UTC by kjk

2023-04-03 00:40 UTC, kjk commented
Hi Rodrigo, great project.

I needed those functions so adding.

I made result of CreateNamedPipe an HFILE because I need to call ReadFile() on it.

It could also return HANDLE or a new type HPIPE but if it was HPIPE, would need to duplicate ReadFile, CloseHandle etc.

Not sure if ConnectNamedPipe() should be methods on HFILE, I made them straightforward args.

2023-04-03 21:10 UTC, rodrigocfd requested changes

2023-04-03 21:10 UTC, rodrigocfd commented on win/co/kernel.go
All constants in Windigo are prefixed with its type. For example:

```go
type SW int32

const (
	SW_HIDE            SW = 0
	SW_SHOWNORMAL      SW = 1
	// and so on...
)
```

So the constants `PIPE_OPEN` and `PIPE_MODE` should be prefixed as well.

Also, `PIPE_UNLIMITED_INSTANCES` should not exist here, since it's not an enumeration. Instead the value in the function should be made optional; when not specified, the library would insert the `255` in place.

2023-04-03 21:21 UTC, rodrigocfd requested changes

2023-04-03 21:21 UTC, rodrigocfd commented on win/funcs_kernel.go
`HPIPE` should have its own type, since it's not the same as `HFILE`. The shared functions should be duplicated for each handle, just like `CloseHandle` exists for various handle types.

2023-04-04 00:31 UTC, kjk commented on win/co/kernel.go
done

2023-04-04 00:32 UTC, kjk commented on win/funcs_kernel.go
done

2023-04-04 01:05 UTC, rodrigocfd approved these changes
Looks great to me now.

2023-04-04 01:05 UTC, merged

2023-04-04 01:41 UTC, kjk commented
Thanks!